INSERT INTO TB_SITUACAO_PEDIDO (ID, NM_SITUACAO) VALUES (1, 'Aguardando Pagamento');
INSERT INTO TB_SITUACAO_PEDIDO (ID, NM_SITUACAO) VALUES (2, 'Cancelado');
INSERT INTO TB_SITUACAO_PEDIDO (ID, NM_SITUACAO) VALUES (3, 'Pago');
